#!/bin/bash
# Autogenerated. Submit with: sbatch /nas/ucb/marimeireles/dev/Collab-Overcooked/slurm-scripts/l5-missing/run_l5_shard_10.sh
sbatch "/nas/ucb/marimeireles/dev/Collab-Overcooked/slurm-scripts/runner_l5_fill_gaps.sh" "/nas/ucb/marimeireles/dev/Collab-Overcooked/slurm-scripts/l5-missing/shard_10.txt"
